### ISSUE TITLE
Some questions about USB

### ISSUE THREAD

**Issue by shahryarjb** [pay64k/pi_dash#7]
Hello, At first, thank you for your efforts. I have some questions about configuring USB and test `OBD`. I am new in Nerves and I want to create a project like you for a car. 
So I am using `circuits_uart` for connection to USB, but I do not know how I can test and get data from a car. It is very hard to prepare ECU and USB `OBD` and a car. So I have no way to test and develop my program.

And the other question, when we want to use `Circuits.UART.write` we should know some specialized String or Integer to connect to `OBD` for example if I write `1` it shows me x data and if I write `"x"` it shows me status of light.

Again I am very sorry, I just want to create an open-source project for analysing cars Which is based on a thesis.

I have read your code, But I could not find a way to order my Bluetooth dongle to start discovery and my mobile can not find its name to connect or something like mobile which helps me to send a file to my Raspberry Pi or receive it instead of testing real ECU in a car.

Thank you.

**Comment by pay64k** [comment]
Hey. For testing without a real car you can use [ELM327-emulator](https://github.com/Ircama/ELM327-emulator). It will start an application on an emulated serial port which you can use to write the commands. 
As for writing the commands: before you can read the data from ECU (if using ELM) you need to perform a "handshake" sequence - there is one test I wrote [here](https://github.com/pay64k/pi_dash/blob/761fa9e8d8b01bbf47bb8085ded9e6f7c6f1b66c/test/elm_connector_test.exs#L105) that you can see this sequence. `assert_wrote` is a message that is sent from application to ELM and `send_to_connector` is from ELM to application. For explanation of perticular commands, PIDs and values you can check [this](https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_01_PID_00). After that sequence is done, then ELM is ready to recieve data -> ask ECU for value -> get response -> translate -> send value back to application. 

The way to talk with ELM is to basically send strings over serial, it also responds with strings. Have a look at some [links](https://github.com/pay64k/pi_dash/blob/main/links.md) I've gathered throughout the development process - they could be useful.

As for BT dongle - I haven't tested with that. In theory when BT connection is established to the dongle from a PC - there is a serial port created, if you use that serial port name in `Circuits.UART.open(uart_port_pid, serial_port, opts)`. 

Let me know how it goes and of course you are welcome to ask any questions here, I will try my best to answer :)

BTW, what is your thesis about?
